version: "0.2"
ignorePaths:
  - /apps/web/src/lib/data/news.json
  - /apps/web/src/lib/data/news_archive.json
  - pnpm-lock.yaml
  - pnpm-workspace.yaml
  - package.json
dictionaryDefinitions: []
dictionaries: []
enableCompoundWords: enable
words:
  - additionality
  - cloudinary
  - Coerver
  - deslugify
  - hygraph
  - Neue
  - Noto
  - OKLCH
  - parentheticals
  - rgba
  - Roboto
  - Segoe
  - skinnypug
  - stylesheet
  - tailwindcss
  - Verra
  - wordmark
import: []
ignoreWords:
  - lorem
  - ipsum
